import type { HeroDef } from '../types';

export const HEROES: HeroDef[] = [
  {
    id: 'paladin',
    name: 'Paladin',
    family: 'warrior',
    role: 'Bulwark',
    color: '#7fb4f2',
    hp: 72,
    atk: 8,
    def: 6,
    evasion: 0.05,
    mitigate: 0.32,
    regen: 0,
    burst: 1,
    rampPerRound: 0,
    rampCap: 0,
    rage: null,
    fearImmune: true,
    resist: [],
    vuln: ['poison'],
    fleeThreshold: 0.12,
    greed: 0.2,
    disarmChance: 0,
    ability: { id: 'brace', name: 'Brace', blurb: 'Raises the shield when wounded — the next room lands soft.' },
    strengths: 'Shrugs off direct hits and fear. Physical rooms barely scratch him.',
    weaknesses: 'Poison and burn tick straight through his armour.'
  },
  {
    id: 'berserker',
    name: 'Berserker',
    family: 'warrior',
    role: 'Bloodrage',
    color: '#e8624a',
    hp: 84,
    atk: 11,
    def: 3,
    evasion: 0,
    mitigate: 0.08,
    regen: 0,
    burst: 1,
    rampPerRound: 0,
    rampCap: 0,
    rage: { hpPct: 0.38, atkMult: 1.7, healPct: 0.2 },
    fearImmune: true,
    resist: [],
    vuln: ['frost'],
    fleeThreshold: 0,
    greed: 0.3,
    disarmChance: 0,
    ability: { id: 'rage', name: 'Rage', blurb: 'Below a third health he heals and hits half again as hard.' },
    strengths: 'Never retreats. Wounding him only makes him worse.',
    weaknesses: 'A Net binds him — bound heroes cannot rage.'
  },
  {
    id: 'trickster',
    name: 'Trickster',
    family: 'rogue',
    role: 'Shadowstep',
    color: '#a483d8',
    hp: 42,
    atk: 9,
    def: 2,
    evasion: 0.45,
    mitigate: 0,
    regen: 0,
    burst: 1,
    rampPerRound: 0,
    rampCap: 0,
    rage: null,
    fearImmune: false,
    resist: [],
    vuln: ['arcane'],
    fleeThreshold: 0.2,
    greed: 0.75,
    disarmChance: 0.5,
    ability: { id: 'vanish', name: 'Vanish', blurb: 'Slips into the dark when cornered and is nearly untouchable.' },
    strengths: 'Dodges half of everything and often disarms traps outright.',
    weaknesses: 'Chill and Net strip the dodge; then anything multi-hit shreds her.'
  },
  {
    id: 'assassin',
    name: 'Assassin',
    family: 'rogue',
    role: 'Opening Strike',
    color: '#cf5f8f',
    hp: 36,
    atk: 14,
    def: 0,
    evasion: 0.18,
    mitigate: 0,
    regen: 0,
    burst: 1.9,
    rampPerRound: 0,
    rampCap: 0,
    rage: null,
    fearImmune: false,
    resist: [],
    vuln: ['fire'],
    fleeThreshold: 0.3,
    greed: 0.6,
    disarmChance: 0.2,
    ability: { id: 'mark', name: 'Death Mark', blurb: 'The first strike of every fight lands with lethal force.' },
    strengths: 'Deletes most single monsters before they act twice.',
    weaknesses: 'Paper thin. Anything that survives the opener kills him.'
  },
  {
    id: 'druid',
    name: 'Druid',
    family: 'mage',
    role: 'Lifebloom',
    color: '#5fc79a',
    hp: 54,
    atk: 8,
    def: 3,
    evasion: 0.1,
    mitigate: 0.08,
    regen: 0.028,
    burst: 1,
    rampPerRound: 0,
    rampCap: 0,
    rage: null,
    fearImmune: false,
    resist: ['poison', 'nature'],
    vuln: ['fire'],
    fleeThreshold: 0.18,
    greed: 0.15,
    disarmChance: 0,
    ability: { id: 'bloom', name: 'Bloom', blurb: 'Draws on the roots below and closes her wounds mid-fight. Fire stops it dead.' },
    strengths: 'Heals every round and shrugs off poison. Outlasts long fights.',
    weaknesses: 'Burning shuts her healing off. Spikes and Ogres end her outright.'
  },
  {
    id: 'elementalist',
    name: 'Elementalist',
    family: 'mage',
    role: 'Risingstorm',
    color: '#f0a34a',
    hp: 38,
    atk: 9,
    def: 0,
    evasion: 0.08,
    mitigate: 0,
    regen: 0,
    burst: 1,
    rampPerRound: 0.18,
    rampCap: 0.7,
    rage: null,
    fearImmune: false,
    resist: ['fire', 'frost'],
    vuln: ['physical'],
    fleeThreshold: 0.25,
    greed: 0.4,
    disarmChance: 0,
    ability: { id: 'surge', name: 'Surge', blurb: 'Every round the storm builds — late fights are his.' },
    strengths: 'Grows stronger each round and shrugs off fire and frost.',
    weaknesses: 'Feeble opener. Weaken, Net or a fast kill deny the storm entirely.'
  }
];

export function heroDef(id: string): HeroDef {
  const h = HEROES.find((x) => x.id === id);
  return h || HEROES[0];
}
