import type { MonsterDef } from '../types';

export const MONSTERS: MonsterDef[] = [
  {
    id: 'goblin',
    name: 'Goblin',
    tag: 'physical',
    hp: 26,
    atk: 5,
    def: 1,
    hpPerLevel: 5,
    atkPerLevel: 0.9,
    hitsPerRound: 2,
    cadence: 1,
    strikesFirst: false,
    defPierce: 0,
    evasion: 0.05,
    splitAt: 0,
    ranged: false,
    applies: null,
    desc: 'Two quick swipes a round. Rolls against dodge twice — brutal once a hero is chilled or bound.',
    goldCost: 14,
    goldValue: 12,
    soulValue: 0
  },
  {
    id: 'archer',
    name: 'Skeleton Archer',
    tag: 'physical',
    hp: 22,
    atk: 9,
    def: 0,
    hpPerLevel: 4,
    atkPerLevel: 1.1,
    hitsPerRound: 1,
    cadence: 1,
    strikesFirst: true,
    defPierce: 0.55,
    evasion: 0,
    splitAt: 0,
    ranged: true,
    applies: null,
    desc: 'Looses an arrow before the hero can close. Half their armour counts for nothing.',
    goldCost: 18,
    goldValue: 15,
    soulValue: 0
  },
  {
    id: 'slime',
    name: 'Slime',
    tag: 'poison',
    hp: 46,
    atk: 5,
    def: 2,
    hpPerLevel: 8,
    atkPerLevel: 0.7,
    hitsPerRound: 1,
    cadence: 1,
    strikesFirst: false,
    defPierce: 0,
    evasion: 0,
    splitAt: 0.5,
    ranged: false,
    applies: { kind: 'poison', rooms: 2 },
    desc: 'Splits in half when wounded and keeps coming. Poisons on contact. Nothing bursts it down.',
    goldCost: 20,
    goldValue: 18,
    soulValue: 1
  },
  {
    id: 'ogre',
    name: 'Ogre',
    tag: 'physical',
    hp: 52,
    atk: 22,
    def: 3,
    hpPerLevel: 9,
    atkPerLevel: 2.4,
    hitsPerRound: 1,
    cadence: 2,
    strikesFirst: false,
    defPierce: 0.2,
    evasion: 0,
    splitAt: 0,
    ranged: false,
    applies: null,
    desc: 'Winds up every other round, then removes most of a hero. Healers cannot out-heal it.',
    goldCost: 26,
    goldValue: 22,
    soulValue: 1
  },
  {
    id: 'shadow',
    name: 'Shadow',
    tag: 'arcane',
    hp: 30,
    atk: 7,
    def: 1,
    hpPerLevel: 6,
    atkPerLevel: 1.2,
    hitsPerRound: 1,
    cadence: 1,
    strikesFirst: false,
    defPierce: 0.3,
    evasion: 0.35,
    splitAt: 0,
    ranged: true,
    applies: { kind: 'fear', rooms: 2 },
    desc: 'Half of what the hero swings passes through it. Its touch frightens them into running early.',
    goldCost: 30,
    goldValue: 26,
    soulValue: 1
  }
];

export function monsterDef(id: string): MonsterDef {
  const m = MONSTERS.find((x) => x.id === id);
  return m || MONSTERS[0];
}

export const LORD = {
  name: 'Nekrokos the Demon Lord',
  short: 'Nekrokos',
  hp: 46,
  atk: 9,
  def: 3,
  hpPerLevel: 14,
  atkPerLevel: 1.8,
  defPerLevel: 0.8,
  hitsPerRound: 1
};
